@default: 
  just --list

test:
  mix test

compile environment="dev": clean update_deps
  MIX_ENV={{environment}} mix compile

update_deps:
  mix deps.get

run_in_shell:
  iex -S mix

run:
  mix run --no-halt

format_code:
  mix format

clean:
  mix deps.clean --all

create-database:
  mix ecto.create

create-migration migration_name:
  mix ecto.gen.migration {{migration_name}}

run-migration-script:
  mix ecto.migrate

rollback-migration-script:
  mix ecto.rollback



